logger:
  file:
    path: /usr/local/var/log/open5gs/ausf.log
  level: info

ausf:
  sbi:
    server:
      - address: 172.20.0.13
        port: 7777
    client:
      nrf:
        - uri: http://172.20.0.10:7777