db_uri: mongodb://172.20.0.2/open5gs

logger:
  file:
    path: /usr/local/var/log/open5gs/pcf.log
  level: info

pcf:
  sbi:
    server:
      - address: 172.20.0.16
        port: 7777
    client:
      nrf:
        - uri: http://172.20.0.10:7777