logger:
  file:
    path: /usr/local/var/log/open5gs/udm.log
  level: info

udm:
  sbi:
    server:
      - address: 172.20.0.12
        port: 7777
    client:
      nrf:
        - uri: http://172.20.0.10:7777