# IMSI / SUPI
supi: 'imsi-001010000000001'

# Home PLMN
mcc: '001'
mnc: '01'

# SUCI Protection Scheme
protectionScheme: 0

homeNetworkPublicKey: '5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650'
homeNetworkPublicKeyId: 1
routingIndicator: '0000'

# Permanent subscription key (K)
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'

# Operator Code (OPc)
op: 'E8ED2441347B7990E92C19B0316CD6FC'
opType: 'OPC'

# Authentication Management Field
amf: '8000'

# Device Identity
imei: '356938035643803'
imeiSv: '4370816125816151'

# UE TUN Interface
tunNetmask: '255.255.0.0'

# Disable Linux Namespace to attach TUNs directly to host
useNamespace: false

# gNB address
gnbSearchList:
  - 127.0.0.1

# UAC configuration
uacAic:
  mps: false
  mcs: false

uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU Sessions (Dual PDU Session setup: internet + ims)
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: 0xffffff
  - type: 'IPv4'
    apn: 'ims'
    slice:
      sst: 1
      sd: 0xffffff

# Configured NSSAI
configured-nssai:
  - sst: 1
    sd: 0xffffff

# Default NSSAI
default-nssai:
  - sst: 1
    sd: 0xffffff

# Integrity algorithms
integrity:
  IA1: true
  IA2: true
  IA3: true

# Ciphering algorithms
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
